import { addClip, createClip, exportMarkdown, searchClips } from "/extension/clip-core.js";

const KEY='tracepin:web-demo:v1'; let clips=[],selected=null,library=false;
const els={capture:document.querySelector('#capturePanel'),library:document.querySelector('#libraryPanel'),form:document.querySelector('#pinForm'),empty:document.querySelector('#selectionEmpty'),text:document.querySelector('#selectedText'),type:document.querySelector('#pinType'),priority:document.querySelector('#pinPriority'),tags:document.querySelector('#pinTags'),note:document.querySelector('#pinNote'),list:document.querySelector('#pinList'),search:document.querySelector('#pinSearch'),count:document.querySelector('#pinCount'),storage:document.querySelector('#storageSize'),mode:document.querySelector('#modeLabel'),dialog:document.querySelector('#exportDialog'),export:document.querySelector('#exportContent'),toast:document.querySelector('#toast')};
const node=(tag,text,className)=>{const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(className)el.className=className;return el};
const notify=(text)=>{els.toast.textContent=text;els.toast.classList.add('show');setTimeout(()=>els.toast.classList.remove('show'),1900)};
function seed(){return [createClip({title:'Demo Atelier 07 — Collection',url:'https://demo-atelier-07.invalid/collection',quote:'Explore the edit',note:'CTA теряется: усилить контраст и назвать действие конкретнее.',tags:['cta','conversion'],type:'ui',priority:'important',viewport:{width:1440,height:900}},{id:'TP-001',now:'2026-08-27T08:42:00.000Z'}),createClip({title:'Demo Atelier 07 — Collection',url:'https://demo-atelier-07.invalid/collection',quote:'$ 840',note:'Цена выглядит как подпись и не считывается как коммерческая информация.',tags:['price','hierarchy'],type:'ui',priority:'blocker',viewport:{width:1440,height:900}},{id:'TP-002',now:'2026-08-27T08:46:00.000Z'})]}
function load(){try{const parsed=JSON.parse(localStorage.getItem(KEY)||'null');clips=Array.isArray(parsed)?parsed:seed()}catch{clips=seed()}save()}
function save(){localStorage.setItem(KEY,JSON.stringify(clips));els.storage.textContent=`${Math.max(1,Math.ceil(new Blob([JSON.stringify(clips)]).size/1024))} KB`}
function setMode(next){library=next;els.capture.hidden=library;els.library.hidden=!library;els.mode.textContent=library?'LIBRARY':'CAPTURE MODE';render()}
function selectElement(element){document.querySelectorAll('[data-capture].selected').forEach((item)=>item.classList.remove('selected'));element.classList.add('selected');selected=element;els.empty.hidden=true;els.form.hidden=false;els.text.textContent=(element.innerText||element.textContent).replace(/\s+/g,' ').trim();els.type.value=element.dataset.type||'text';els.priority.value=element.dataset.priority||'normal';els.tags.value='';els.note.value=element.dataset.note||''}
function clearSelection(){document.querySelectorAll('[data-capture].selected').forEach((item)=>item.classList.remove('selected'));selected=null;els.form.hidden=true;els.empty.hidden=false}
function render(){els.count.textContent=clips.length;els.list.replaceChildren();const visible=searchClips(clips,els.search.value);visible.forEach((pin,index)=>{const row=node('article',undefined,'pin-row');row.append(node('span',String(index+1).padStart(2,'0')),node('i',undefined,pin.priority));const body=node('div');body.append(node('b',pin.quote),node('p',pin.note),node('small',`${pin.type} · ${pin.tags.map((tag)=>'#'+tag).join(' ')||'без тегов'}`));row.append(body);els.list.append(row)});save()}
document.querySelectorAll('[data-capture]').forEach((element)=>element.addEventListener('click',(event)=>{event.preventDefault();selectElement(element)}));
els.form.addEventListener('submit',(event)=>{event.preventDefault();if(!selected)return;const input={title:'Demo Atelier 07 — Collection',url:'https://demo-atelier-07.invalid/collection',quote:(selected.innerText||selected.textContent).replace(/\s+/g,' ').trim(),note:els.note.value,tags:els.tags.value,type:els.type.value,priority:els.priority.value,viewport:{width:innerWidth,height:innerHeight},anchor:{locator:selected.tagName.toLowerCase()+'[data-capture]'}};const result=addClip(clips,input);if(result.created){clips=result.clips;notify('Правка добавлена')}else notify('Такая правка уже есть');clearSelection();setMode(true)});
document.querySelector('#cancelPin').addEventListener('click',clearSelection);document.querySelector('#libraryButton').addEventListener('click',()=>setMode(!library));document.querySelector('#backToCapture').addEventListener('click',()=>setMode(false));els.search.addEventListener('input',render);document.querySelector('#exportPreview').addEventListener('click',()=>{els.export.textContent=exportMarkdown(searchClips(clips,els.search.value),{exportedAt:'2026-08-27T09:00:00.000Z'});els.dialog.showModal()});document.querySelector('#closeExport').addEventListener('click',()=>els.dialog.close());document.querySelector('#resetDemo').addEventListener('click',()=>{clips=seed();clearSelection();setMode(false);notify('Демо восстановлено')});load();setMode(false);
