import { inspectContainerConfig, redactEnvironment, transitionRelease, validateReleaseConfig, verifyBackup } from './release.js';

export class ReleaseDockDemo{
  constructor({dockerfile,compose,state,backupReport,releaseReport,env={}}){this.dockerfile=dockerfile;this.compose=compose;this.stateFile=state;this.backupReport=backupReport;this.releaseReport=releaseReport;this.env=env;this.reset();}
  reset(){this.release={version:this.env.RELEASE_VERSION??'1.0.0',environment:this.env.RELEASE_ENV??'demo',status:'planned',events:[{status:'planned',note:'Runbook подготовлен',at:'2026-08-27T10:00:00.000Z'}]};this.clock=0;return this.state();}
  now(){return new Date(Date.parse('2026-08-27T10:04:00.000Z')+this.clock++*4*60000);}
  state(){const config={version:this.release.version,environment:this.release.environment,healthPath:'/health',backupRetention:7},container=inspectContainerConfig({dockerfile:this.dockerfile,compose:this.compose}),backup=this.backupReport?.manifest&&this.backupReport?.content?verifyBackup(this.backupReport.content,this.backupReport.manifest):{valid:false,reason:'NOT_RUN'};return{release:structuredClone(this.release),config:{...config,validation:validateReleaseConfig(config)},container,stateFile:structuredClone(this.stateFile),backup:{...backup,report:this.backupReport??null},verification:this.releaseReport??null,environment:redactEnvironment(this.env),boundary:'Local Docker proof · no registry · no TLS · no remote host · no CI provider'};}
  action(action){if(action==='reset')return{result:{title:'Runbook сброшен',detail:'Выпуск снова на этапе planned.',tone:'neutral'},state:this.reset()};const steps={build:['building','Образ собран из зафиксированного Dockerfile.'],health:['healthy','Health endpoint отвечает, container gates пройдены.'],promote:['promoted','Версия отмечена активной в локальной репетиции.'],rollback:['rolled_back','Runbook вернул локальную метку на предыдущую версию.']};if(!steps[action])throw new Error('UNKNOWN_ACTION');const[status,note]=steps[action];if(status==='healthy'&&!this.state().container.ready)throw new Error('CONTAINER_GATES_FAILED');this.release=transitionRelease(this.release,status,note,this.now());return{result:{title:status==='promoted'?'Версия активна':status==='rolled_back'?'Rollback отмечен':note,detail:`Статус: ${status}`,tone:status},state:this.state()};}
}
