import { PublicWatch } from './src/watch.js';

const watch = new PublicWatch();
const $ = (id) => document.getElementById(id);
const nodes = { source: $('sourceFilter'), category: $('categoryFilter'), state: $('stateFilter'), query: $('query'), list: $('feedList'), visible: $('visibleCount'), total: $('totalMetric'), changed: $('changedMetric'), sources: $('sourceMetric'), detailSource: $('detailSource'), detailUrl: $('detailUrl'), title: $('detailTitle'), summary: $('detailSummary'), categoryValue: $('detailCategory'), budget: $('detailBudget'), date: $('detailDate'), changeTitle: $('changeTitle'), changes: $('changeList'), tags: $('detailTags'), log: $('log'), update: $('updateButton'), toast: $('toast') };
let selectedKey = null; let updated = false;
const escapeHtml = (value) => { const span = document.createElement('span'); span.textContent = value ?? ''; return span.innerHTML; };
const dateLabel = (value) => new Intl.DateTimeFormat('ru', { day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit' }).format(new Date(value));

function filters() { return { source: nodes.source.value, category: nodes.category.value, state: nodes.state.value, query: nodes.query.value }; }
function showToast(message) { nodes.toast.textContent = message; nodes.toast.classList.add('show'); clearTimeout(showToast.timer); showToast.timer = setTimeout(() => nodes.toast.classList.remove('show'), 2300); }
function renderFacets() { const facets = watch.facets(); const add = (node, values, current) => { const first = node.options[0].outerHTML; node.innerHTML = first + values.map((v) => `<option value="${escapeHtml(v)}">${escapeHtml(v)}</option>`).join(''); node.value = values.includes(current) ? current : 'all'; }; add(nodes.source, facets.sources, nodes.source.value); add(nodes.category, facets.categories, nodes.category.value); }
function renderList() { const items = watch.list(filters()); if (!items.some((item) => item.key === selectedKey) && items[0]) selectedKey = items[0].key; nodes.visible.textContent = String(items.length).padStart(2, '0'); nodes.list.innerHTML = items.length ? items.map((item) => `<button class="feed-card ${item.key === selectedKey ? 'active' : ''}" data-key="${escapeHtml(item.key)}"><header><span>${escapeHtml(item.source)}</span><time>${dateLabel(item.publishedAt)}</time></header><h3>${escapeHtml(item.title)}</h3><p>${escapeHtml(item.category)} · ${escapeHtml(item.budget)}</p><footer><span class="state ${item.state}">${item.state === 'changed' ? 'Изменено' : 'Новая'}</span><b>${item.tags.length} метки</b></footer></button>`).join('') : '<div class="empty"><b>Совпадений нет</b><p>Измените фильтры или поисковый запрос.</p></div>'; }
function renderDetail() { if (!selectedKey) return; let item; try { item = watch.get(selectedKey); } catch { return; } nodes.detailSource.textContent = item.source; nodes.detailUrl.title = item.url; nodes.title.textContent = item.title; nodes.summary.textContent = item.summary; nodes.categoryValue.textContent = item.category; nodes.budget.textContent = item.budget; nodes.date.textContent = dateLabel(item.publishedAt); nodes.changeTitle.textContent = item.changes.length ? `Изменено полей: ${item.changes.length}` : 'Новая запись'; nodes.changes.innerHTML = item.changes.length ? item.changes.map((field) => `<li>${escapeHtml(({ title:'Название', category:'Категория', budget:'Бюджет', publishedAt:'Дата', summary:'Описание', tags:'Метки' })[field] ?? field)}</li>`).join('') : '<li>Ранее не встречалась в локальном наборе</li>'; nodes.tags.innerHTML = item.tags.map((tag) => `<span>${escapeHtml(tag)}</span>`).join(''); }
function renderLog() { nodes.log.innerHTML = watch.history().slice(0, 8).map((event) => `<li class="${event.type}"><i></i><div><b>${escapeHtml(event.title)}</b><span>${escapeHtml(event.source)} · ${dateLabel(event.at)}</span></div></li>`).join(''); }
function renderSummary() { const summary = watch.summary(); nodes.total.textContent = summary.total; nodes.changed.textContent = summary.changed; nodes.sources.textContent = summary.sources; }
function render() { renderFacets(); renderSummary(); renderList(); renderDetail(); renderLog(); }
async function ingest(url) { const response = await fetch(url); if (!response.ok) throw new Error('feed_unavailable'); return watch.ingest(await response.json()); }
function download(format) { const content = format === 'csv' ? watch.toCSV() : watch.toJSON(); const blob = new Blob([content], { type: format === 'csv' ? 'text/csv;charset=utf-8' : 'application/json;charset=utf-8' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = `public-watch.${format}`; link.click(); setTimeout(() => URL.revokeObjectURL(link.href), 0); showToast(`${format.toUpperCase()} подготовлен локально`); }
nodes.list.addEventListener('click', (event) => { const card = event.target.closest('[data-key]'); if (!card) return; selectedKey = card.dataset.key; render(); if (matchMedia('(max-width:760px)').matches) document.querySelector('.detail').scrollIntoView({ behavior: 'smooth' }); });
[nodes.source, nodes.category, nodes.state].forEach((node) => node.addEventListener('change', render)); nodes.query.addEventListener('input', render);
nodes.update.addEventListener('click', async () => { if (updated) { showToast('Обновление уже сравнено'); return; } nodes.update.disabled = true; try { const result = await ingest('./fixtures/feed-update.json'); updated = true; render(); showToast(`Новых: ${result.added} · изменённых: ${result.changed}`); } catch { showToast('Не удалось обновить демо-данные'); } finally { nodes.update.disabled = false; } });
document.querySelectorAll('[data-export]').forEach((button) => button.addEventListener('click', () => download(button.dataset.export)));
ingest('./fixtures/feed-initial.json').then(() => render()).catch(() => showToast('Не удалось загрузить локальные демо-данные'));
